### ISSUE TITLE
Incomplete redirects aren't handled properly when followed by '|'

### ISSUE THREAD

**Issue by 0x416c6941** [mcombeau/minishell#3]
This command:
`cat >`
Returns:

> minishell: syntax error near unexpected token `newline'

<br>

Which is fine. However, e.g. this one:
`cat > | cat`
Is handled incorrectly, and instead just creates a file called "|", whilst the second command is ignored.

**Comment by mcombeau** [comment]
Hello,
Good catch ! Thank you for taking the time to find the issue and make a pull request, but we won't be merging it. We'd like this repository to stay as it was when we submitted the code for evaluation. Feel free to keep improving your own fork of it, though !
Good luck on your 42 projects ;)
